env:
  browser: true
  es6: true
  mocha: true
parser: 'babel-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    classes: true
settings:
  react:
    pragma: React
    version: 16.8.0